### ISSUE TITLE
Comment here to be added as a collaborator

### ISSUE THREAD

**Issue by gusshawstewart** [githubschool/green-giant#1]
### Comment below - you can say anything 
 We will all be using this repository today. Even though it's public right now, you will not be able to make changes until you're given the correct permissions. We've automated this process via the GitHub API and some fancy chatops. Once you comment, we will add you as a collaborator. 

  You'll also start to receive a lot of emails. (:exclamation:) You can slow these down immediately by clicking the 'Unwatch' button and selecting either the 'Participating and @mentions' or 'Ignoring' option.

**Comment by gusshawstewart** [comment]
hello!

**Comment by dgtl-n0md** [comment]
Hi :)

**Comment by KopIlya** [comment]
Hello!

**Comment by very-anonymous** [comment]
Hey there

**Comment by aruchibarudo** [comment]
who is there?

**Comment by gusshawstewart** [comment]
@gusshawstewart

**Comment by rageofgods** [comment]
hi there

**Comment by Bright-Burn** [comment]
hello there

**Comment by rkadim** [comment]
Hello

**Comment by Shaggart** [comment]
hi there

**Comment by Bright-Burn** [comment]
You were the Chosen One

**Comment by gusshawstewart** [comment]
anything you like

**Comment by levurevich** [comment]
+

**Comment by rustem-mustaev** [comment]
hi

**Comment by RenatSeredzhinov** [comment]
hi

**Comment by andreypazuhanich** [comment]
Spasibo!

**Comment by BelalovBM** [comment]
Hello from Ufa !!!

**Comment by eldoranstars** [comment]
123

**Comment by gusshawstewart** [comment]
hello!

**Comment by BelalovBM** [comment]
Hello, you did some records of our lessons, how can we get it ?
